version: 0.3.{build}
clone_depth: 1
init:
- ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- cmd: >-
    set PROJ_DIR=%CD%

    set QTBIN=c:\qt\5.10\mingw53_32\bin

    set SSLDIR=C:\QT\TOOLS\MINGW530_32\OPT\BIN

    set MAKE=c:\MinGW\bin\mingw32-make.exe

    set CHOCO=c:\ProgramData\chocolatey\bin\choco.exe

    set INNO=c:\Program Files (x86)\Inno Setup 5\ISCC.exe


    %QTBIN%\qtenv2.bat

    cd "%PROJ_DIR%"

    %QTBIN%\qmake src

    %MAKE% -j4

    %MAKE% clean

    copy /Y %SSLDIR%\ssleay32.dll Release\

    copy /Y %SSLDIR%\libeay32.dll Release\

    %QTBIN%\windeployqt.exe --libdir Release Release\qmtn.exe

    tree /f /a Release

    %CHOCO% install innosetup

    mv assets\qmtn_create_setup.iss .

    cp icons\qmtn.ico release

    "%INNO%" qmtn_create_setup.iss

    cd release

    mv *.exe "%PROJ_DIR%"

#before_test:
#- ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
- path: ./*.exe
  name: qmtn-win32.exe
- path: Release
  name: Release

on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
