version: 0.2.{build}
clone_depth: 1
init:
- ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- cmd: >-
    set PROJ_DIR=%CD%

    set QTBIN=c:\qt\5.8\mingw53_32\bin

    set MAKE=c:\MinGW\bin\mingw32-make.exe

    set CHOCO=c:\ProgramData\chocolatey\bin\choco.exe

    set INNO=c:\Program Files (x86)\Inno Setup 5\ISCC.exe


    %QTBIN%\qtenv2.bat

    cd "%PROJ_DIR%"

    %QTBIN%\qmake

    %MAKE% -j4

    %MAKE% clean

    %QTBIN%\windeployqt.exe --libdir Release Release\qmtn.exe

    %CHOCO% install innosetup

    mv assets\qmtn_create_setup.iss .

    cp icons\qmtn.ico release

    "%INNO%" qmtn_create_setup.iss

    cd release

    mv *.exe "%PROJ_DIR%"

#before_test:
#- ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
- path: ./*.exe
  name: qmtn-win32.exe

on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
