stages:
    - build

fedora_rawhide:
    image: fedora:rawhide
    stage: build
    before_script:
    - dnf --nogpgcheck -y install gcc-c++ qt5-qtbase-devel qt5-qtwebengine-devel make
    script:
    - qmake-qt5.sh CONFIG+=use_webengine src
    - make
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 30 week
        paths:
        - ./qmtn
centOS7:
    image: centos:7
    stage: build
    before_script:
    - yum -y install gcc-c++ qt5-qtbase-devel make
    script:
    - qmake-qt5 src
    - make
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 30 week
        paths:
        - ./qmtn
