stages:
    - build

.fc: &fedora
    stage: build
    before_script:
    - dnf -y install gcc-c++ qt5-qtbase-devel make
    script:
    - qmake-qt5 src
    - make
fc28:
    image: fedora:28
    <<: *fedora
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 30 week
        paths:
        - ./qmtn
fc29:
    image: fedora:29
    <<: *fedora
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 30 week
        paths:
        - ./qmtn

fc-rawhide:
    image: fedora:rawhide
    <<: *fedora
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 30 week
        paths:
        - ./qmtn
