stages:
    - build

.fc: &fedora
    stage: build
    only:
    - master
    - devel
    script:
    - dnf -y install gcc-c++ qt5-qtbase-devel rpm-build make
    - tar czf archive.tar.gz * --transform="s%^%qmtn-ci/%"
    - mkdir -p buildroot/SOURCES
    - mv archive.tar.gz buildroot/SOURCES/
    - rpmbuild -bb --define "_topdir $(pwd)/buildroot" buildrpm/qmtn.spec
    - mv buildroot/RPMS/x86_64/*.rpm .

fc26:
    image: fedora:26
    <<: *fedora
#    when: manual
    artifacts:
        name: qmtn-fc26
        expire_in: 30 week
        paths:
        - ./*.rpm

fc27:
    image: fedora:27
    <<: *fedora
#    when: manual
    artifacts:
        name: qmtn-fc27
        expire_in: 30 week
        paths:
        - ./*.rpm
