stages:
    - build

.fc: &fedora
    stage: build
    only:
    - master
    - devel
    before_script:
    - dnf -y install gcc-c++ qt5-qtbase-devel make
    script:
    - qmake-qt5 mtngui.pro
    - make

fc27:
    image: fedora:27
    <<: *fedora
#    when: manual
    artifacts:
        name: qmtn-fc27
        expire_in: 30 week
        paths:
        - ./*.rpm

fc28:
    image: fedora:28
    <<: *fedora
    artifacts:
        name: qmtn-fc28
        expire_in: 30 week
        paths:
        - ./*.rpm


fc29:
    image: fedora:29
    <<: *fedora
    artifacts:
        name: qmtn-fc29
        expire_in: 30 week
        paths:
        - ./*.rpm
